spring:
  #  profiles:
  #    active: dev
  application:
    name: imooc-springboot-study

server:
  servlet:
    context-path: /imooc
  port: 8000

imooc:
  springboot:
    version: 2.1,2.1.4
    name: study

management:
  endpoint:
    shutdown:
      enabled: true # 最特殊的监控端点
  endpoints:
    web:
      exposure:
        include: "*" # 打开所有的监控点

#127.0.0.1:8000/imooc/actuator/health  健康
# /imooc/actuator/info

info:
  app:
    name: imooc-springboot-study
    groupId: com.imooc.springboot.study
    version:  0.0.1-SNAPSHOT
